[versions]
# Kotlin
kotlin = "2.2.20"

# Plugins
shadow = "8.1.1"
blossom = "2.1.0"
idea-ext = "1.1.7"

# Loom
loom = "1.11-SNAPSHOT"
architectury-plugin = "3.4-SNAPSHOT"

# Common
cobblemon = "1.7.1+1.21.1"
sgui = "1.6.1+1.21.1"

# Fabric
fabric-loader = "0.17.2"
fabric-api = "0.116.6+1.21.1"
fabric-kotlin = "1.13.6+kotlin.2.2.20"
fabric-permissions-api = "0.3.1"
debugutils-fabric = "1.21.1-1.0.9-fabric"

# NeoForge
neoforge = "21.1.182"
neo-kotlin-for-forge = "5.10.0"
debugutils-forge = "1.21.1-1.0.9-neoforge"

[libraries]
# General Buildscript Plugins
kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
loom = { group = "dev.architectury", name = "architectury-loom", version.ref = "loom" }
architectury = { group = "architectury-plugin", name = "architectury-plugin.gradle.plugin", version.ref = "architectury-plugin" }
shadow = { group = "com.github.johnrengelman", name = "shadow", version.ref = "shadow" }
blossom = { group = "net.kyori", name = "blossom", version.ref = "blossom" }
ideaExt = { group = "org.jetbrains.gradle.plugin.idea-ext", name = "org.jetbrains.gradle.plugin.idea-ext.gradle.plugin", version.ref = "idea-ext"}

# Kotlin
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }

#Common
cobblemon = { group = "com.cobblemon", name = "mod", version.ref = "cobblemon" }
cobblemon-fabric = { group = "com.cobblemon", name = "fabric", version.ref = "cobblemon" }
cobblemon-neoforge = { group = "com.cobblemon", name = "neoforge", version.ref = "cobblemon" }
sgui = { group = "eu.pb4", name = "sgui", version.ref = "sgui" }

# Fabric
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
fabric-kotlin = { group = "net.fabricmc", name = "fabric-language-kotlin", version.ref = "fabric-kotlin" }
fabric-permissions = { group = "me.lucko", name = "fabric-permissions-api", version.ref = "fabric-permissions-api" }
fabric-debugutils = { group = "maven.modrinth", name = "debugutils", version.ref = "debugutils-fabric"}

# NeoForge
neoforge = { group = "net.neoforged", name = "neoforge", version.ref = "neoforge" }
neo-kotlin-forge = { group = "thedarkcolour", name = "kotlinforforge-neoforge", version.ref = "neo-kotlin-for-forge" }
neoforge-debugutils = { group = "maven.modrinth", name = "debugutils", version.ref = "debugutils-forge"}

[bundles]
kotlin = [ "kotlin-stdlib", "kotlin-reflect" ]
fabric = [ "fabric-kotlin", "fabric-permissions" ]


